---
title: "Checking Risk Slim"
author: "Hallee Wong"
date: "3/10/2018"
output: html_document
---

````{r}
spam = read.csv("./data/spambase_data.csv")
source("/Users/Hallee/Desktop/thesis/roc.R")
````

+--------------------------------------+-------------------+-----------+
| P(Y = +1) = 1/(1 + exp(0 - score))   |                   |           |
| ==================================== | ================= | ========= |
| CharFreqDollarSign                   |          5 points |   + ..... |
| WordFreqRemove                       |          4 points |   + ..... |
| WordFreqHP                           |         -2 points |   + ..... |
| WordFreqGeorge                       |         -5 points |   + ..... |
| ==================================== | ================= | ========= |
| ADD POINTS FROM ROWS 1 to 4          |             SCORE |   = ..... |
+--------------------------------------+-------------------+-----------+
error_rate: 12.43
TPR: 93.18
FPR: 5.41
true_positives: 1339
false_positives: 98
true_negatives: 2690
false_negatives: 474

total examples = 4601

```{r}
coefs = c(0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.,
        0., -5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  5.,  0.,  0.,  0.,  0)

scores = sign(as.matrix(spam[,2:length(coefs)]) %*% as.matrix(coefs[2:length(coefs)]))
```

Clasify was positive iff. score > 0 
Clasify negative if score <= 0 
```{r}
pos_ind = spam$Spam == 1
sum(scores[pos_ind] == 1)
sum(scores[!pos_ind] == 1)
sum(scores[!pos_ind] != 1)
sum(scores[pos_ind] != 1)
```

```{r}
probs = 1/(1 + exp(-c(as.matrix(spam[,2:length(coefs)]) %*% as.matrix(coefs[2:length(coefs)]))))
hist(probs)
getROC(probs, spam$Spam)
plotOnePredvsObs(probs, spam$Spam)
```

Why are the scores wrong using `RowSums()`?
```{r}
m1 = c(1,3)
m2 = data.frame(x1=c(0,1), x2=c(1,1), x3=c(0,1))

m1*m2
m2*m1
```
